blog/urls.py
from django.urls import path, re_path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('about/', views.AboutView.as_view(), name='about'),
    re_path(r'^post/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='post_detail'),
    path('post/new/', views.PostCreateView.as_view(), name='post_create'),
    re_path(r'^post/(?P<pk>\d+)/update/$', views.PostUpdateView.as_view(), name='post_update'),
    re_path(r'^post/(?P<pk>\d+)/publish/$', views.publish_post, name='publish_post'),
    re_path(r'^post/(?P<pk>\d+)/delete/$', views.PostDeleteView.as_view(), name='post_delete'),
    path('drafts/', views.DraftListView.as_view(), name='draft_list'),
    re_path(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    re_path(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    re_path(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
]

company_blog/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.contrib.auth.views import LogoutView,LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^accounts/login/', LoginView.as_view(redirect_authenticated_user=True), name='login'),
    re_path(r'^accounts/logout/', LogoutView.as_view(next_page='/'), name='logout'),
    re_path(r'^', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse_lazy, reverse
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=128)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    published = models.DateTimeField(null=True, blank=True)

    def __str__(self):
        return '{}: {}'.format(self.author.username, self.title)

    def publish(self):
        self.published = timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk':self.pk})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.CharField(max_length=64)
    text = models.TextField()
    create_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def __str__(self):
        return self.text

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('blog:post_list')

blog/forms.py
from django import forms
from blog import models

class PostForm(forms.ModelForm):

    class Meta:
        model = models.Post
        fields = ('author', 'title', 'text')

        widgets = {
            'title': forms.TextInput(attrs={'class':'textinputclass'}),
            'text': forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = models.Comment
        fields = ('author', 'text')

        widgets = {
            'author': forms.TextInput(attrs={'class':'textinputclass'}),
            'text': forms.Textarea(attrs={'class': 'editable medium-editor-textarea commentcontent'})
        }

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (CreateView, DeleteView, UpdateView,
                                  DetailView, ListView, TemplateView)
from blog import models, forms
from django.utils import timezone

# Create your views here.

class AboutView(TemplateView):
    template_name = 'about.html'


class PostDetailView(DetailView):
    model = models.Post


class PostListView(ListView):
    model = models.Post

    def get_queryset(self):
        return models.Post.objects.filter(published__lte=timezone.now()).order_by('-published')


class PostCreateView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    redirect_field_name = '/'

    model = models.Post
    form_class = forms.PostForm


class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/login/'
    redirect_field_name = '/'

    model = models.Post
    form_class = forms.PostForm


class PostDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/login/'

    model = models.Post
    success_url = reverse_lazy('blog:post_list')


class DraftListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = '/'

    model = models.Post
    template_name = 'blog/post_draft_list.html'

    def get_queryset(self):
        return models.Post.objects.filter(published__isnull=True).order_by('create_date')

#=====================================================================================================================

@login_required
def publish_post(request, pk):
    post = get_object_or_404(models.Post, pk=pk)
    post.publish()
    return redirect(reverse('blog:post_detail', kwargs={'pk':pk}))


@login_required
def add_comment_to_post(request, pk):
    post = get_object_or_404(models.Post, pk=pk)

    if request.method == 'POST':
        form = forms.CommentForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()

            return redirect(reverse('blog:post_detail', kwargs={'pk':post.pk}))

    else:
        form = forms.CommentForm()

    return render(request, 'blog/comment_form.html', {'form':form})


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(models.Comment,pk=pk)

    comment.approve()
    return redirect(reverse('blog:post_detail', kwargs={'pk':comment.post.pk}))


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(models.Comment, pk=pk)

    post_pk = comment.post.pk
    comment.delete()
    return redirect(reverse('blog:post_detail', kwargs={'pk':post_pk}))

blog/templates/blog/about.html
{% extends 'blog/base_blog.html' %}

{% block content %}
  <div class="jumbotron">
    <h1>Welcome to My Blog!</h1>
    <p class="lead">Thanks for visiting my site!</p>
  </div>
{% endblock %}

blog/templates/blog/base_blog.html
<!DOCTYPE html>
{% load static %}
<html lang="de">
<head>
  <meta charset="UTF-8">
  <title>Company Blog</title>

{#  Bootstrap #}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

{#  Medium Style Editor#}
  <script src="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/js/medium-editor.min.js"></script>
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/medium-editor@latest/dist/css/medium-editor.min.css"
        type="text/css" media="screen" charset="utf-8">

{#  Custom Styles#}
  <link rel="stylesheet" href="{% static 'css/blog.css' %}">

{#  Fonts#}
  <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">

</head>

<body class="loader">

{#Navbar#}
<nav class="navbar navbar-expand-xl navbar-light bg-light navbar-static-top techfont custom-navbar">
  <div class="container">
    <a class="navbar-brand bigbrand" href="{% url 'blog:post_list' %}">My Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:about' %}">About</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="https://www.github.com/">Github</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="https://www.linkedin.com/">LinkedIn</a>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:post_create' %}">New Post</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:draft_list' %}">Drafts</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>

          <li class="nav-item">
            <span class="navbar-text">Welcome {{ user.username }}</span>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
        {% endif %}
      </ul>

    </div>
  </div>

</nav>


<div class="container content">
  <div class="row">
    <div class="col-md-8">
      <div class="blog_posts">
        {% block content %}
        {% endblock %}
      </div>
    </div>
  </div>
</div>

<script
  src="https://code.jquery.com/jquery-3.3.1.min.js"
  integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
  crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

blog/templates/blog/comment_form.html
{% extends 'blog/base_blog.html' %}

{% block content %}
  <h1>Add a comment</h1>
  <form class="post-form" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit" class="save btn btn-primary">Add Comment</button>
  </form>

  <script>var editor= new MediumEditor('.editable');</script>
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base_blog.html' %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete {{ object }}?</p>
    <button class="btn btn-danger">Delete</button>
    <a class="btn btn-primary" href="{% url 'blog:post_list' %}">Cancel</a>
  </form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base_blog.html' %}

{% block content %}
  <h1 class="posttitle loader">{{ post.title }}</h1>
  {% if post.published %}
    <div class="postdate">
      Published: {{ post.published|date:'d. M. Y' }}
    </div>

  {% else %}
    <a class="btn btn-primary" href="{% url 'blog:publish_post' pk=post.pk %}">Publish</a>
  {% endif %}
  <p class="postcontent">{{ post.text|safe|linebreaksbr }}</p>

  {% if user.is_authenticated %}
    <a class="btn btn-primary" href="{% url 'blog:post_update' pk=post.pk %}">Edit Post</a>
    <a class="btn btn-danger" href="{% url 'blog:post_delete' pk=post.pk %}">Delete Post</a>
  {% endif %}

  <hr>
  <a class="btn btn-primary btn-comment" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add Comment</a>

  <div class="container">
    {% for comment in post.comments.all %}
      {% if user.is_authenticated or comment.approved_comment %}
        <br>
        Created: {{ comment.create_date|date:'d. M. Y' }}
        {% if not comment.approved_comment %}
          <a class="btn btn-primary" href="{% url 'blog:comment_approve' pk=comment.pk %}">Approve Comment</a>
          <a class="btn btn-danger" href="{% url 'blog:comment_remove' pk=comment.pk %}">Delete Comment</a>
        {% endif %}

        <p>{{ comment.text|safe|linebreaksbr }}</p>
        <p>Posted by: {{ comment.author }}</p>
      {% endif %}
    {% empty %}
      <p>No Comments</p>
    {% endfor %}
  </div>
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base_blog.html' %}

{% block content %}
  {% for post in post_list %}
    <div class="post">
      <p class="date">Created: {{ post.create_date|date:'d. M. Y' }}</p>
      <h1><a href="{% url 'blog:post_detail'  pk=post.pk%}">{{ post.title }}</a></h1>
      <p>{{ post.text|truncatechars:200 }}</p>
    </div>
  {% empty %}
    <p>No posts in draft state</p>
  {% endfor %}
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base_blog.html' %}

{% block content %}
  <h1>New Post</h1>
  <form class="post-form" method="post">
    {%  csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="save_widget btn btn-primary">Submit</button>
  </form>

  <script>var editor= new MediumEditor('.editable');</script>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base_blog.html' %}

{% block content %}
  <div class="mx-auto">
    {% for post in post_list %}
      <div class="post">
        <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
        <div class="date">
          <p>Published on: {{ post.published|date:"d. M. Y" }}</p>
          <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments: {{ post.approve_comments.count }}</a>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}